### ISSUE TITLE
Failed to establish a new connection: [Errno 61] Connection refused',))

### ISSUE THREAD

**Issue by scheung38** [tiepologian/neospatial-py#1] opened 2015-10-12 15:56 UTC
Why 

```
index = spatial.createIndex('geom')
```

returns

```
File "/Users/scheung/anaconda/envs/venv/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='localhost', port=7474): Max retries exceeded with url: /db/data/index/node/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x106322850>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

Likely to be company behind firewall?

**Comment by tiepologian** [comment] 2015-10-12 16:31
Hi!

Please make sure that neo4j is running and that the neospatial plugin has been installed!
If everything is running, it could be the firewall

**Comment by scheung38** [comment] 2015-10-13 08:29
Ok neo4j now running but still:

```
Traceback (most recent call last):
  File "/Users/scheung/PycharmProjects/Demo/__init__.py", line 13, in <module>
    index = spatial.createIndex('geom')
  File "/Users/scheung/anaconda/envs/venv/lib/python2.7/site-packages/neospatial.py", line 19, in createIndex
    raise Exception("Error Executing Query")
Exception: Error Executing Query
```

**Comment by tiepologian** [comment] 2015-10-13 09:05
Hi, can you post your code so I can do a few tests?

**Comment by tiepologian** [comment] 2015-10-13 09:20
Hi @scheung38 

I believe I have found what causes your problem: by default Neo4j now enables HTTP authentication, while the neospatial plugin does not support auth headers.

Try this: disable Neo4j auth by editing the configuration file:

```
sudo nano /etc/neo4j/neo4j-server.properties
```

look for the line "dbms.security.auth_enabled" and set it to "false".

```
dbms.security.auth_enabled=false
```

then restart Neo4j

```
sudo service neo4j-service restart
```

Your code should now work ;-)

**Comment by scheung38** [comment] 2015-10-13 11:50
Changed as you mentioned to false, restarted neo4j and still same error exception query message? from : 

```
spatial = SpatialConnection("localhost", 7474)
index = spatial.createIndex('geom') <- Coming from here
```

returns

```
raise Exception("Error Executing Query")
```

**Comment by tiepologian** [comment] 2015-10-13 13:10
@scheung38 

Can you please post me the output of this command?

curl http://localhost:7474/db/data/

**Comment by scheung38** [comment] 2015-10-13 14:35
same as before

**Comment by scheung38** [comment] 2015-10-13 14:49
```
(venv)localhost:neo4j scheung$ curl http://localhost:7474/db/data/
{
  "extensions" : { },
  "node" : "http://localhost:7474/db/data/node",
  "node_index" : "http://localhost:7474/db/data/index/node",
  "relationship_index" : "http://localhost:7474/db/data/index/relationship",
  "extensions_info" : "http://localhost:7474/db/data/ext",
  "relationship_types" : "http://localhost:7474/db/data/relationship/types",
  "batch" : "http://localhost:7474/db/data/batch",
  "cypher" : "http://localhost:7474/db/data/cypher",
  "indexes" : "http://localhost:7474/db/data/schema/index",
  "constraints" : "http://localhost:7474/db/data/schema/constraint",
  "transaction" : "http://localhost:7474/db/data/transaction",
  "node_labels" : "http://localhost:7474/db/data/labels",
  "neo4j_version" : "2.2.5"
}(venv)localhost:neo4j scheung$
```

**Comment by tiepologian** [comment] 2015-10-13 14:52
Hi @scheung38 

As you can see from the above output, the neospatial plugin is not installed!
If the plugin is correctly installed you would see it in the "extension" list in the previous output.

This is the correct procedure to install the plugin:

1) Download the plugin (https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.15-neo4j-2.2.3/neo4j-spatial-0.15-neo4j-2.2.3-server-plugin.zip?raw=true)

2) Unzip the plugin inside the neo4j plugins directory (usually /var/lib/neo4j/plugins)

3) Restart Neo4j

Have you done all the above steps?

**Comment by scheung38** [comment] 2015-10-13 15:02
But already Version  0.1.0 installed:

```
(venv) $ pip install neospatial
Requirement already satisfied (use --upgrade to upgrade): neospatial in /Users/scheung/anaconda/envs/venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.1 in /Users/scheung/anaconda/envs/venv/lib/python2.7/site-packages (from neospatial)

from flask import Flask
from neospatial import *

app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello World!'


spatial = SpatialConnection("localhost", 7474)
index = spatial.createIndex('geom')

node1 = spatial.createNode(45.46775, 9.21056, {'name': 'Gold Restaurant'})
spatial.addNodeToIndex(node1, index)

node2 = spatial.createNode(45.48107, 9.19997, {'name': 'Ristorante Da Giannino'})
spatial.addNodeToIndex(node2, index)

result = spatial.findWithinDistance(index, 45.48608, 9.20018, 5)
for i in result:
    print i['data']['name']

if __name__ == '__main__':
    app.run()
```

and cmd click neospatial takes me to:

```
#!/usr/bin/python

import requests
import json

class SpatialConnection:
    def __init__(self, host, port):
        self.hostname = host
        self.port = port
        return

    def createIndex(self, name):
        payload = {"name":name, "config":{"provider":"spatial","geometry_type":"point","lat":"lat","lon":"lon"}}
        headers = {'content-type': 'application/json', 'accept': 'application/json'}
        r = requests.post("http://"+self.hostname+":"+str(self.port)+"/db/data/index/node/", data=json.dumps(payload), headers=headers)
        if r.status_code == 200 or r.status_code == 201:
            return name
        else:
            raise Exception("Error Executing Query")

    def createNode(self, lat, lon, props={}):
        payload = {"lat":lat,"lon":lon}
        payload.update(props)
        headers = {'content-type': 'application/json', 'accept': 'application/json'}
        r = requests.post("http://"+self.hostname+":"+str(self.port)+"/db/data/node/", data=json.dumps(payload), headers=headers)
        if r.status_code == 200 or r.status_code == 201:
            return r.json()['self']
        else:
            raise Exception("Error Executing Query")

    def addNodeToIndex(self, node, index):
        payload = {"layer":index,"node":node}
        headers = {'content-type': 'application/json', 'accept': 'application/json'}
        r = requests.post("http://"+self.hostname+":"+str(self.port)+"/db/data/ext/SpatialPlugin/graphdb/addNodeToLayer", data=json.dumps(payload), headers=headers)
        if r.status_code == 200 or r.status_code == 201:
            return node
        else:
            raise Exception("Error Executing Query")

    def findWithinDistance(self, index, lat, lon, distance):
        payload = {"layer":index,"pointY":lat,"pointX":lon,"distanceInKm":distance}
        headers = {'content-type': 'application/json', 'accept': 'application/json'}
        r = requests.post("http://"+self.hostname+":"+str(self.port)+"/db/data/ext/SpatialPlugin/graphdb/findGeometriesWithinDistance", data=json.dumps(payload), headers=headers)
        if r.status_code == 200 or r.status_code == 201:
            result = []
            for i in r.json():
                result.append({'id':i['self'],'data':i['data']})
            return result
        else:
            raise Exception("Error Executing Query")

    def findWithinBoundingBox(self, index, minX, maxX, minY, maxY):
        payload = {"layer":index,"minx":minX,"maxx":maxX,"miny":minY,"maxy":maxY}
        headers = {'content-type': 'application/json', 'accept': 'application/json'}
        r = requests.post("http://"+self.hostname+":"+str(self.port)+"/db/data/ext/SpatialPlugin/graphdb/findGeometriesInBBox", data=json.dumps(payload), headers=headers)
        if r.status_code == 200 or r.status_code == 201:
            result = []
            for i in r.json():
                result.append({'id':i['self'],'data':i['data']})
            return result
        else:
            raise Exception("Error Executing Query")

```

if it is not installed properly, Pycharm would say Unresolved when hovering the import line and the  SpatialConnection class instance: 

```
from neospatial import *
:
:
spatial = SpatialConnection("localhost", 7474) 
```

**Comment by tiepologian** [comment] 2015-10-13 15:09
@scheung38 

The problem is not the neospatial Python plugin, but the neospatial server plugin that also needs to be installed! Follow the instructions in my previous post ;-)

**Comment by scheung38** [comment] 2015-10-13 15:18
I don't have /var/lib/neo4j/plugins directory, is it automatically created or I need to create it manually in Mac OSX?

**Comment by tiepologian** [comment] 2015-10-13 15:20
Oh OK, on OS X it's different... Where have you installed Neo4j? Look in the installation directory, you should have a plugins folder! You need to unzip the zip file in that plugin folder ;-)

**Comment by scheung38** [comment] 2015-10-13 15:23
/Users/scheung/Downloads/neo4j-community-2.2.5/plugins, so drag the neo4j-spatial-0 folder into here then?

**Comment by tiepologian** [comment] 2015-10-13 15:25
Yes, that 's the correct folder. Download the neo4j plugin from the link i posted before and unzip all the content inside that folder! There should be a few jar files in the zip file

**Comment by scheung38** [comment] 2015-10-13 15:35
So all the jars are now in :

```
/Users/scheung/Downloads/neo4j-community-2.2.5/plugins/neo4j-spatial-0
```

or 

```
/Users/scheung/Downloads/neo4j-community-2.2.5/plugins
```

Because tried placing all jar files in BOTH, 

```
from flask import Flask
from neospatial import *

app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello World Digital City!'


spatial = SpatialConnection("localhost", 7474)
index = spatial.createIndex('geom')

node1 = spatial.createNode(45.46775, 9.21056, {'name': 'Gold Restaurant'})
spatial.addNodeToIndex(node1, index)

node2 = spatial.createNode(45.48107, 9.19997, {'name': 'Ristorante Da Giannino'})
spatial.addNodeToIndex(node2, index)

result = spatial.findWithinDistance(index, 45.48608, 9.20018, 5)
for i in result:
    print i['data']['name']

if __name__ == '__main__':
    app.run()
```

restarted neo4j and also restarted Pycharm IDE

Traceback (most recent call last):
  File "/Users/scheung/PycharmProjects/GrowthMapper/**init**.py", line 16, in <module>
    spatial.addNodeToIndex(node1, index)
  File "/Users/scheung/anaconda/envs/venv/lib/python2.7/site-packages/neospatial.py", line 38, in addNodeToIndex
    raise Exception("Error Executing Query")
Exception: Error Executing Query

Process finished with exit code 1

$ curl http://localhost:7474/db/data/
{
  "extensions" : {
    "SpatialPlugin" : {
      "addSimplePointLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/addSimplePointLayer",
      "addNodesToLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/addNodesToLayer",
      "findClosestGeometries" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/findClosestGeometries",
      "addGeometryWKTToLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/addGeometryWKTToLayer",
      "addEditableLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/addEditableLayer",
      "findGeometriesWithinDistance" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/findGeometriesWithinDistance",
      "addCQLDynamicLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/addCQLDynamicLayer",
      "addNodeToLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/addNodeToLayer",
      "getLayer" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/getLayer",
      "findGeometriesInBBox" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/findGeometriesInBBox",
      "updateGeometryFromWKT" : "http://localhost:7474/db/data/ext/SpatialPlugin/graphdb/updateGeometryFromWKT"
    }
  },
  "node" : "http://localhost:7474/db/data/node",
  "node_index" : "http://localhost:7474/db/data/index/node",
  "relationship_index" : "http://localhost:7474/db/data/index/relationship",
  "extensions_info" : "http://localhost:7474/db/data/ext",
  "relationship_types" : "http://localhost:7474/db/data/relationship/types",
  "batch" : "http://localhost:7474/db/data/batch",
  "cypher" : "http://localhost:7474/db/data/cypher",
  "indexes" : "http://localhost:7474/db/data/schema/index",
  "constraints" : "http://localhost:7474/db/data/schema/constraint",
  "transaction" : "http://localhost:7474/db/data/transaction",
  "node_labels" : "http://localhost:7474/db/data/labels",
  "neo4j_version" : "2.2.5"

**Comment by tiepologian** [comment] 2015-10-13 15:38
@scheung38 

OK, now the plugin is installed! Now the error is in a different query...before the error was in the "create index" query, now it is in the "add node to index" query...

**Comment by scheung38** [comment] 2015-10-13 15:40
this one:

```
spatial.addNodeToIndex(node1, index)
```

Same as tutorial?

**Comment by tiepologian** [comment] 2015-10-13 15:57
@scheung38 

I'm doing a few tests... it seems this is a bug in the server plugin... I will do a few tests and I'll let you know!

**Comment by scheung38** [comment] 2015-10-13 16:32
which folder structure to put all jar files:

```
/Users/scheung/Downloads/neo4j-community-2.2.5/plugins/neo4j-spatial-0
```

or

```
/Users/scheung/Downloads/neo4j-community-2.2.5/plugins
```

**Comment by tiepologian** [comment] 2015-10-13 17:04
/Users/scheung/Downloads/neo4j-community-2.2.5/plugins

**Comment by tiepologian** [comment] 2015-10-14 10:05
Hi @scheung38 

I've updated the package.

Update the Python module by running

```
sudo pip install neospatial --upgrade
```

and update your code by adding this line before creating the index:

```
spatial.createLayer('geom')
```

Your code should now look like:

```
from neospatial import *

spatial = SpatialConnection("localhost", 7474)
spatial.createLayer('geom')
index = spatial.createIndex('geom')

node1 = spatial.createNode(45.46775, 9.21056, {'name':'Gold Restaurant'})
spatial.addNodeToIndex(node1, index)

node2 = spatial.createNode(45.48107, 9.19997, {'name':'Ristorante Da Giannino'})
spatial.addNodeToIndex(node2, index)

result = spatial.findWithinDistance(index, 45.48608, 9.20018, 5)
for i in result:
    print i['data']['name']
```

Let me know if it works!

**Comment by tiepologian** [comment] 2015-10-16 08:52
Closing issue - let me know if you have anymore issues ;-)

**Closed as completed by tiepologian** 2015-10-16 08:52 UTC
Labels: support, not a bug
